version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
     - mongo
     - redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
      image: redis
      ports:
          - "6379"
